### ISSUE TITLE
Kafka errors show up even if Kafka is disabled in config file

### ISSUE THREAD

**Issue by gruyaume** [omec-project/smf#195]
## Description

In a setup where Kafka is disabled (see config file below), the SMF logs kafka errors. Here I don't expect kafka calls to be made at all.

Config file (partial):

```yaml
info:
  version: 1.0.0
  description: SMF initial local configuration

configuration:
  smfDBName: sdcore_smf
  enableDBStore: false
  enableUPFAdapter: false
  debugProfilePort: 5001
  mongodb:
    url: <mongo url>
  kafkaInfo:
    enableKafka: false
  smfName: SMF
  sbi:
    scheme: https
    registerIPv4: smf.sdcore.svc.cluster.local
    bindingIPv4: 0.0.0.0
    port: 29502
    tls:
      key: /support/TLS/smf.key
      pem: /support/TLS/smf.pem
  serviceNameList:
    - nsmf-pdusession
    - nsmf-event-exposure
    - nsmf-oam
  pfcp:
    addr: 10.1.182.9
  nrfUri: https://nrf:29510
```

### Logs

```
2023-11-30T21:01:28.315Z [smf] 2023-11-30T21:01:28Z [ERRO][SMF][Kafka] kafka send message write error: [dial tcp: lookup sd-core-kafka-headless on 10.152.183.10:53: no such host]
```
